-- MySQL Script generated by MySQL Workbench
-- Sun Mar 13 21:03:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema warehouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema warehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `warehouse` DEFAULT CHARACTER SET utf8 ;
USE `warehouse` ;

-- -----------------------------------------------------
-- Table `warehouse`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warehouse`.`warehouse` (
  `id_warehouse` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`id_warehouse`),
  UNIQUE INDEX `id_warehouse_UNIQUE` (`id_warehouse` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouse`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warehouse`.`employee` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NULL,
  `id_warehouse` INT NOT NULL,
  PRIMARY KEY (`id_employee`, `id_warehouse`),
  UNIQUE INDEX `id_employee_UNIQUE` (`id_employee` ASC) VISIBLE,
  INDEX `fk_employee_warehouse1_idx` (`id_warehouse` ASC) VISIBLE,
  CONSTRAINT `fk_employee_warehouse1`
    FOREIGN KEY (`id_warehouse`)
    REFERENCES `warehouse`.`warehouse` (`id_warehouse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouse`.`producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warehouse`.`producer` (
  `id_producer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`id_producer`),
  UNIQUE INDEX `id_producer_UNIQUE` (`id_producer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouse`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warehouse`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `production_date` DATE NOT NULL,
  `weight` DECIMAL(15,2) NULL,
  `id_producer` INT NOT NULL,
  PRIMARY KEY (`id_product`, `id_producer`),
  INDEX `fk_product_producer1_idx` (`id_producer` ASC) INVISIBLE,
  UNIQUE INDEX `id_product_UNIQUE` (`id_product` ASC) VISIBLE,
  CONSTRAINT `fk_product_producer1`
    FOREIGN KEY (`id_producer`)
    REFERENCES `warehouse`.`producer` (`id_producer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouse`.`warehouse_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warehouse`.`warehouse_has_product` (
  `id_warehouse_has_product` INT NOT NULL AUTO_INCREMENT, 
  `date_of_delivery` DATE NOT NULL,
  `shipment_date` DATE NOT NULL,
  `id_warehouse` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id_warehouse_has_product`, `id_warehouse`, `id_product`),
  INDEX `fk_warehouse_has_product_product1_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `fk_warehouse_has_product_warehouse`
    FOREIGN KEY (`id_warehouse`)
    REFERENCES `warehouse`.`warehouse` (`id_warehouse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warehouse_has_product_product1`
    FOREIGN KEY (`id_product`)
    REFERENCES `warehouse`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
